name: Go CI

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"

      - name: Run unit tests
        run: go test -v